Repository pomerium/datasource, pull requests merged in 2024-07, with the labels that each got.

#343 datasource/okta: refactor okta provider
  cmd/pomerium-datasource/directory.go
  go.mod
  go.sum
  pkg/directory/okta/config.go
  pkg/directory/okta/okta.go
  pkg/directory/okta/okta_test.go
  pkg/directory/okta/provider.go
Labels: bug

#349 replace ::set-output in release-tagged action
  .github/workflows/release-tagged.yml
Labels: ci

#350 update to github.com/vektah/gqlparser/v2
  go.mod
  go.sum
  pkg/directory/github/github_test.go
Labels: dependency, go
